# Setup
title: 'the missing semester of your cs education'
url: https://missing-semester-cn.github.io

# Settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
permalink: /:title/
future: true
# safe: true # breaks local rendering if enabled
timezone: Asia/Shanghai
# analytics:
#   tracking_id: UA-53167467-11

collections:
  '2019':
    output: true
  '2020':
    output: true
  'blogs':
    output: true
  'blogs_learning':
    # relative_directory: './blogs/learning'
    # relative_directory: '_blogs'
    output: true
  'blogs_weekly':
    # relative_directory: './_blogs/learning'
    output: true
    


# Excludes
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-titles-from-headings

titles_from_headings:
  enabled:     true
  strip_title: false
  collections: true
